// <auto-generated />
namespace UlasimApp.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lineupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lineupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201710161453162_line-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
